
import { GoogleGenAI } from "@google/genai";
import { ProcessingOptions } from "../types";

const GEMINI_MODEL = 'gemini-2.5-flash-image';

const sleep = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

export const processIdPhoto = async (
  imageBase64: string,
  options: ProcessingOptions
): Promise<string> => {
  const apiKey = process.env.API_KEY;
  if (!apiKey) {
    throw new Error("API Key is missing.");
  }

  const ai = new GoogleGenAI({ apiKey });

  // Clean base64 string if it has prefix
  const base64Data = imageBase64.split(',')[1] || imageBase64;

  const parts: any[] = [
      {
        inlineData: {
          mimeType: 'image/jpeg',
          data: base64Data
        }
      }
  ];

  let prompt = "";
  
  // If user provided a full custom prompt (advanced mode), use it directly
  if (options.customPrompt) {
    prompt = options.customPrompt;
  } else {
    // Construct a structured prompt for ID photo generation
    let bgInstruction = "";
    if (options.color === 'original') {
        bgInstruction = "1. DO NOT change the background. Keep the background from the original image EXACTLY as it is.";
    } else {
        const colorDesc = options.color.startsWith('#') ? `solid hex color ${options.color}` : `solid ${options.color} color`;
        bgInstruction = `1. Change the background of the subject to a ${colorDesc}. The background must be perfectly solid and uniform.`;
    }
    
    let outfitInstruction = "Keep the person's clothing EXACTLY as it is in the original image.";
    
    // Check for Visual Outfit Reference
    if (options.outfitImage) {
        const outfitBase64 = options.outfitImage.split(',')[1] || options.outfitImage;
        // Add the outfit image as the SECOND part
        parts.push({
            inlineData: {
                mimeType: 'image/jpeg',
                data: outfitBase64
            }
        });

        outfitInstruction = `
        STRICT INSTRUCTION: OUTFIT REPLACEMENT
        - Image 1 is the SUBJECT.
        - Image 2 is the REFERENCE CLOTHING.
        - ACTION: Completely REMOVE the subject's original clothing and REPLACE it with the clothing from Image 2.
        - The new clothing must fit the subject's body naturally.
        - DO NOT overlay the new clothing on top of the old clothing. The old clothing must be 100% replaced.
        - Match the skin tone at the neck/shoulders if exposed.
        `;
    } 

    prompt = `
      You are an expert professional ID photo editor.
      
      Input(s): 
      - The first image is the subject (portrait).
      ${options.outfitImage ? '- The second image is the target outfit.' : ''}
      
      Tasks:
      ${bgInstruction}
      2. ${outfitInstruction}
      
      3. CRITICAL - IDENTITY PRESERVATION:
         - You MUST preserve the subject's original face, hair strands, hairline, ears, nose, mouth, moles, and skin texture EXACTLY.
         - DO NOT perform "beautification", smoothing, or feature alteration.
         - The facial identity must remain 100% identical to the source.

      4. GEOMETRY & ALIGNMENT:
         - Rotate the image so the head is perfectly vertical (plumb line).
         - Level the eyes horizontally.
         - BALANCE THE SHOULDERS: Ensure both shoulders are symmetrical, level, and at the same height. If one shoulder is higher, correct it.

      5. COMPOSITION (TIGHT CROP):
         - The framing must be a standard ID photo close-up.
         - The head and upper shoulders should fill approximately 75-85% of the frame.
         - Crop tightly: The top of the hair/head should be very close to the top edge of the image (minimal headroom).
         - The face should be centered horizontally.

      6. Output ONLY the modified image of the subject.
    `;
  }

  // Add the text prompt as the last part
  parts.push({ text: prompt });

  const maxRetries = 3;
  let attempt = 0;

  while (attempt <= maxRetries) {
    try {
        const response = await ai.models.generateContent({
        model: GEMINI_MODEL,
        contents: {
            parts: parts
        }
        });

        // Check for image in response parts
        const responseParts = response.candidates?.[0]?.content?.parts;
        if (responseParts) {
            for (const part of responseParts) {
                if (part.inlineData && part.inlineData.data) {
                    return `data:${part.inlineData.mimeType || 'image/png'};base64,${part.inlineData.data}`;
                }
            }
        }
        
        throw new Error("No image generated by Gemini.");
    } catch (error: any) {
        // Attempt to extract status code or error message
        const status = error.status || error.code || (error.response ? error.response.status : null);
        const message = error.message || JSON.stringify(error);
        
        const isQuotaError = status === 429 || 
                             status === 'RESOURCE_EXHAUSTED' || 
                             message.includes('429') || 
                             message.includes('quota') ||
                             message.includes('RESOURCE_EXHAUSTED');
        
        const isServerBusy = status === 503 || message.includes('503');

        if ((isQuotaError || isServerBusy) && attempt < maxRetries) {
            attempt++;
            // Exponential backoff: 2s, 4s, 8s
            const delay = 2000 * Math.pow(2, attempt - 1);
            console.warn(`Gemini API Error (${status}). Retrying in ${delay}ms... (Attempt ${attempt}/${maxRetries})`);
            await sleep(delay);
            continue;
        }

        // If we can't retry or max retries reached, throw specific friendly error
        if (isQuotaError) {
             console.error("Gemini Quota Exceeded:", error);
             throw new Error("Hệ thống đang quá tải (Quota Exceeded). Vui lòng đợi 1-2 phút rồi thử lại.");
        }
        
        console.error("Gemini API Error:", error);
        throw error;
    }
  }
  
  throw new Error("Failed to process image after retries.");
};
